#import "BasePopup.h"

#define EXTRAS_ART_GOOBER @"extras_art_goober.png"
#define EXTRAS_ART_MOEMOERUSH @"extras_art_moemoerush.png"
#define EXTRAS_ART_PENGMAKU @"extras_art_pengmaku.png" 
#define EXTRAS_ART_WINDOWCLEANER @"extras_art_window_cleaner.png"

#define EXTRAS_ART_OLDLOGO @"extras_art_oldlogo.png"
#define EXTRAS_ART_GANG @"extras_art_gang.png"
#define EXTRAS_ART_WORLD4_EARLY @"extras_art_world4_early.png"
#define EXTRAS_ART_OLDDOG @"extras_art_olddog.png"
#define EXTRAS_ART_WORLD1_PROGRESS @"extras_art_world1_progress.png"
#define EXTRAS_ART_LABASSETS @"extras_art_labassets.png"
#define EXTRAS_ART_LOGOHEAD @"extras_art_logohead.png"
#define EXTRAS_ART_LABENTRANCE @"extras_art_labentrance_concept.png"
#define EXTRAS_ART_INTRO_FRAME1 @"extras_art_intro_frame1.png"
#define EXTRAS_ART_DOGS_FINAL @"extras_art_dogs_final.png"
#define EXTRAS_ART_LAB_FINAL @"extras_art_lab_final.png"
#define EXTRAS_ART_WORLD3_EARLY @"extras_art_world3_early.png"
#define EXTRAS_ART_SUN @"extras_art_sun.png"
#define EXTRAS_ART_WORLD5_EARLY @"extras_art_world5_early.png"
#define EXTRAS_ART_GOSTRICH @"extras_art_gostrich.png"
#define EXTRAS_ART_MENU4 @"extras_art_menu_concept4.png"
#define EXTRAS_ART_MENU3 @"extras_art_menu_concept3.png"
#define EXTRAS_ART_MENU2 @"extras_art_menu_concept2.png"
#define EXTRAS_ART_MENU1 @"extras_art_menu_concept1.png"
#define EXTRAS_ART_TUTORIAL2 @"extras_art_tutorial_concept2.png"
#define EXTRAS_ART_TUTORIAL1 @"extras_art_tutorial_concept.png"
#define EXTRAS_ART_WORLD2_EARLY @"extras_art_world2_early.png"
#define EXTRAS_ART_WORLD1_EARLY @"extras_art_world1_early.png"
#define EXTRAS_ART_DOG_FINAL @"extras_art_dog_final.png"
#define EXTRAS_ART_ROBOTS @"extras_art_robots_concept.png"
#define EXTRAS_ART_BOSS @"extras_art_boss_concept.png"
#define EXTRAS_ART_ITEMS @"extras_art_item_concept.png"
#define EXTRAS_ART_LAB @"extras_art_labconcept.png"
#define EXTRAS_ART_BIRTHDAY @"extras_art_birthday.png"

@interface ExtrasArtPopup : BasePopup
+(ExtrasArtPopup*)cons_key:(NSString*)key;
@end
